# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: angelo97
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: rimac-server
# "service" is the name of this project. This will also be added to your AWS resource names.
service: rimac-crud

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
            - 'translate:TranslateText'
          Resource: 
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-*-${sls:stage}
            - arn:aws:translate:${aws:region}:${aws:accountId}:*

functions:
  addFilm:
    handler: src/add_film.addFilm
    events:
      - httpApi:
          path: /film
          method: post
  getFilms:
    handler: src/get_films.getFilms
    events:
      - httpApi:
          path: /films
          method: get
  setFilms:
    handler: src/set_films.setFilms
    events:
      - httpApi:
          path: /films
          method: post

resources:
  Resources:
    FilmTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: ${self:service}-filmTable-${sls:stage}
